### ISSUE TITLE
Milestone 5

### ISSUE THREAD

**Issue by matthewconnell** [kristinawright/group_09-1#14]
Hi @kristinawright 

The `app.R` in your root directory doesn't seem to have been updated since last week? Is the dashboard somewhere else? Did you forget to push something?  Let me know!

**Comment by kristinawright** [comment]
Ahh sorry I pushed to my branch and forgot to merge it to master @matthewconnell.  I have merged them now!

**Comment by matthewconnell** [comment]
Okay! Looks great, and I'll leave you some feedback as soon as possible.
